#!/usr/bin/expect -f

set timeout 30;

set code [lindex $argv 0]
set password [lindex $argv 1] 
set command [lrange $argv 2 end] 

eval spawn $command

expect "Enter passphrase*"

send -- "$password\r"

expect "Verification code*"

send -- "$code\r"

expect ".cpp.nonlive's password*"

send -- "$password\r"
 
expect ".cpp.nonlive's password*"

send -- "$password\r"
 
expect ".cpp.nonlive's password*"

send -- "$password\r"

interact